# ============================================================
# Voyagers of Nera - Dedicated Server (Community Image)
# Non-commercial Docker image (PolyForm Noncommercial License 1.0.0)
# ============================================================

FROM steamcmd/steamcmd:debian-12

RUN dpkg --add-architecture i386 && \
    apt update && \
    apt install -y wine64 xvfb && \
    apt clean autoclean && \
    apt autoremove -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /voyagers_server

COPY ./config/start.sh /start.sh
COPY ./config/CustomGameUserSettings.ini /CustomGameUserSettings.ini

# Ports
EXPOSE 7780/tcp 7780/udp
EXPOSE 27015/tcp 27015/udp

# Metadata
LABEL base.image="steamcmd/steamcmd:debian-12"
LABEL maintainer="Athena"
LABEL version="0.1.0"
LABEL license="PolyForm Noncommercial License 1.0.0"
LABEL copyright="(c) 2025 Athena"


ENTRYPOINT ["bash", "/start.sh"]
