version: "3.9"

services:
  voyagers-server:
    image: athenadock/docker-of-nera:latest
    container_name: docker-of-nera
    restart: "no"
    environment:
      - WINEDEBUG=-all
      - WINEPREFIX=/wineprefix
    volumes:
      - ./data:/voyagers_server/BoatGame/Saved
    ports:
      - "27700:27700/udp"
      - "27800:27800/udp"
    deploy:
      resources:
        limits:
          cpus: "${MAX_CPUS:-2.0}"
          memory: "${MAX_MEMORY:-6G}"
        reservations:
          cpus: "${RESERVED_CPUS:-1.0}"
          memory: "${RESERVED_MEMORY:-2G}"
    labels:
      org.opencontainers.image.title: "Voyagers of Nera Dedicated Server (Community Edition)"
      org.opencontainers.image.license: "PolyForm Noncommercial License 1.0.0"
      org.opencontainers.image.authors: "Athena <ton@email>"
