# ============================================================
# Voyagers of Nera - Dedicated Server (Community Image)
# Non-commercial Docker image (PolyForm Noncommercial License 1.0.0)
# ============================================================

FROM steamcmd/steamcmd:debian-12

RUN dpkg --add-architecture i386 && \
    apt update && \
    apt install -y wine64 xvfb && \
    apt clean autoclean && \
    apt autoremove -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /voyagers_server

COPY ./start.sh /start.sh

# Ports
EXPOSE 27700/udp
EXPOSE 27800/udp

# Métadonnées
LABEL license="PolyForm Noncommercial License 1.0.0"
LABEL copyright="(c) 2025 Athena"


ENTRYPOINT ["bash", "/start.sh"]
