services:
  voyagers-server:
    image: athenamirage/docker-of-nera:latest
    container_name: docker-of-nera
    restart: "no"
    environment:
      - WINEDEBUG=-all
      - WINEPREFIX=/wineprefix
    volumes:
      - ./data:/voyagers_server/BoatGame/Saved
    ports:
      - "7780:7780/udp"
      - "7780:7780/tcp"
      - "27015:27015/udp"
    networks:
      - voyagers-server
    deploy:
      resources:
        limits:
          cpus: "${MAX_CPUS:-2.0}"
          memory: "${MAX_MEMORY:-6G}"
        reservations:
          cpus: "${RESERVED_CPUS:-1.0}"
          memory: "${RESERVED_MEMORY:-2G}"
    labels:
      org.opencontainers.image.title: "Voyagers of Nera Dedicated Server (Community Edition)"
      org.opencontainers.image.license: "PolyForm Noncommercial License 1.0.0"
      org.opencontainers.image.authors: "Athena"
networks:
    voyagers-server:
      driver: bridge