# ============================================================
# Voyagers of Nera - Dedicated Server (Community Image)
# Non-commercial Docker image (PolyForm Noncommercial License 1.0.0)
# ============================================================

FROM steamcmd/steamcmd:debian-12

# Install i386 architecture
RUN dpkg --add-architecture i386
RUN apt update

# Install dependencies.
RUN apt install -y wine64
RUN apt install -y xvfb

#Cleanup
RUN apt clean autoclean
RUN apt autoremove -y
RUN rm -rf /var/lib/apt/lists/*

# Setup environment
WORKDIR /voyagers_server

COPY ./config/start.sh /start.sh
COPY ./config/CustomGameUserSettings.ini /CustomGameUserSettings.ini

# Convert Windows CRLF to LF and make start script executable
RUN sed -i 's/\r$//' /start.sh && chmod +x /start.sh

# Ports
EXPOSE 7780/tcp 7780/udp
EXPOSE 27015/tcp 27015/udp

# Metadata
LABEL base.image="steamcmd/steamcmd:debian-12"
LABEL maintainer="Athena"
LABEL version="0.1.1"
LABEL license="PolyForm Noncommercial License 1.0.0"
LABEL copyright="(c) 2025 Athena"


ENTRYPOINT ["bash", "/start.sh"]
