# ============================================================
# Voyagers of Nera - Dedicated Server (Community Image)
# Non-commercial Docker image (PolyForm Noncommercial License 1.0.0)
# ============================================================

FROM steamcmd/steamcmd:alpine-3

# Install dependencies.
RUN apk update
RUN apk add  wine xvfb --no-cache

#Cleanup
RUN rm -rf /var/lib/apk/lists/*

# Setup environment
WORKDIR /voyagers_server

COPY ./config/start.sh /start.sh
COPY ./config/CustomGameUserSettings.ini /CustomGameUserSettings.ini

# Ports
EXPOSE 7780/tcp 7780/udp
EXPOSE 27015/tcp 27015/udp

# Metadata
LABEL base.image="steamcmd/steamcmd:debian-12"
LABEL maintainer="Athena"
LABEL version="0.1.1"
LABEL license="PolyForm Noncommercial License 1.0.0"
LABEL copyright="(c) 2025 Athena"

ENTRYPOINT ["bash", "/start.sh"]
